version: '3.3'
networks:
    default:
        driver: bridge
services:
    postgres:
        image: postgres:latest
        networks: 
            - default
        environment:
            - POSTGRES_DB=blog-api
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 1m
    blog-api:
        image: go-gin-blog-api-example:latest
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        networks: 
            - default
        environment: 
            - DATABASE_HOST=postgres
            - DATABASE_PORT=5432
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_NAME=blog-api
