name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Compile
      run: make build
    - name: Run Test
      run: go test ./tests/...
    - name: Build Docker Image
      run: docker build -t go-gin-blog-api-example:latest .
